### ISSUE TITLE
Listar las ventajas de Git

### ISSUE THREAD

**Issue by edgarduart23** [edgarduart23/Proyecto-Grupo-Estudio#1]

**Comment by carla1790** [comment]
**Ventajas de Git:**

•Sistema distribuido, que permite el trabajo incluso sin conexión.
•Super rápido y ligero, optimizado para hacer operaciones de control muy rápidas.
•Crear ramas y mezclarlas, poco propenso a problemas.
•La integridad de la información está asegurada gracias a su modelo de almacenamiento, que permite predecir este tipo de problemas.
•Permite flujos de trabajo muy flexibles.
•El concepto de área de preparación o staging permite versionar los cambios como nos convenga, no todo o nada.
•Operaciones locales
•Copias instantáneas
