### ISSUE TITLE
Explicar brevemente los artefactos en Scrum

### ISSUE THREAD

**Issue by edgarduart23** [edgarduart23/Proyecto-Grupo-Estudio#2]

**Comment by carla1790** [comment]
Los artefactos en Scrum son:

***Pila del Producto (Product Backlog)**

Es un inventario que contiene cualquier tipo de trabajo que haya que hacer en el producto: requerimientos, casos de uso, tareas y dependencias. Es la principal fuente de información sobre el producto en Scrum, una lista, que contiene todos los requerimientos que necesitamos implementar en el producto. Esta lista es el resultado del trabajo del Product Owner con el cliente, los stakeholders, sponsors, etc. y refleja el estado real del trabajo pendiente de implementar en el producto, así como el ya realizado. 

***Pila del Sprint (Sprint Backlog)**

Es una lista de elementos en los que trabajar durante la etapa de Sprint. Estos elementos normalmente se componen de tareas técnicas más pequeñas que permiten conseguir un incremento de software terminado. Permite visualizar, durante cada Sprint, aquellos elementos que aún no han empezado a desarrollarse, aquellos que sí y quiénes están trabajando en los mismos, así como aquellos que están esperando a desplegarse o están terminados.


***Incremento (Increment)**

Es el resultado del Sprint, es la suma de todas las tareas, casos de uso, historias de usuario y cualquier elemento que se haya desarrollado durante el Sprint y que será puesto a disposición del usuario final en forma de software, aportando un valor de negocio al producto que se está desarrollando.
