### ISSUE TITLE
Describir los objetivos del modelo relacional

### ISSUE THREAD

**Issue by edgarduart23** [edgarduart23/Proyecto-Grupo-Estudio#5]

**Comment by AnyAcosta23** [comment]
* Independencia Física: La forma de almacenar los datos, no debe influir en su manipulación lógica.
* Independencia Lógica: Las aplicaciones que utilizan la bases de datos no deben ser modificadas por que se modifiquen elementos de la base de datos.
* Flexibilidad: La base de datos ofrece fácilmente distintas vistas en función de los usuarios y aplicaciones.
* Uniformidad: Las estructuras lógicas siempre tienen una única forma conceptual (las tablas).
* Sencillez.
